<p align="center"><span style="font-family: Arial, serif;"><span style="font-size: medium;"><span style="text-decoration: underline;"><strong>Go Solar Terms Of Use</strong></span></span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;"><em>This Agreement was last modified on October 20</em></span></span><span style="color: #000000;"><sup><span style="font-family: Arial, serif;"><em>th</em></span></sup></span><span style="color: #000000;"><span style="font-family: Arial, serif;"><em>, 2016..</em></span></span></span></span></p>
<p><br /><br /></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;">Please read these Terms of Service completely using Go Solar application which is owned and operated by Go Solar LLC. This Agreement documents the legally binding terms and conditions attached to the use of Go Solar Application by Go Solar LLC.</span></span></span></span></p>
<p><a name="_GoBack"></a> <span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;">By using or accessing the App in any way, viewing or browsing the App, or adding your own content to the App, you are agreeing to be bound by these Terms of Service.</span></span></span></span></p>
<p><br /><br /></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;"><span style="text-decoration: underline;">Intellectual Property</span></span></span></span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;">The Site and all of its original content are the sole property of Go Solar LLC and are, as such, fully protected by the appropriate international copyright and other intellectual property rights laws.</span></span></span></span></p>
<p><br /><br /></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;"><span style="text-decoration: underline;">Termination</span></span></span></span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;">Go Solar LLC reserves the right to terminate your access to the Site, without any advance notice.</span></span></span></span></p>
<p><br /><br /></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;"><span style="text-decoration: underline;">Governing Law</span></span></span></span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;">This Agreement is governed in accordance with the laws of Florida, United States.</span></span></span></span></p>
<p><br /><br /></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;"><span style="text-decoration: underline;">Changes to This Agreement</span></span></span></span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;">Go Solar LLC reserves the right to modify these Terms of Service at any time. We do so by posting and drawing attention to the updated terms on the Site. Your decision to continue to visit and make use of the Site after such changes have been made constitutes your formal acceptance of the new Terms of Service.</span></span></span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;">Therefore, we ask that you check and review this Agreement for such changes on an occasional basis. Should you not agree to any provision of this Agreement or any changes we make to this Agreement, we ask and advise that you do not use or continue to access the Go Solar LLC site immediately.</span></span></span></span></p>
<p><br /><br /></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;"><span style="text-decoration: underline;">Contact Us</span></span></span></span></span></p>
<p><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: Arial, serif;">If you have any questions about this Agreement, please feel free to contact us at</span></span><span style="color: #000000;"><span style="font-family: Arial, serif;">&nbsp;</span></span><span style="color: #000000;"><span style="font-family: Arial, serif;">info@gosolarprogram.com.</span></span></span></span></p>